// <auto-generated />
using System;
using ComparisonEngine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ComparisonEngine.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210401130817_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.EShop", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("eshops", "comparison_engine");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("double precision");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("products", "comparison_engine");
                });

            modelBuilder.Entity("Domain.RealProduct", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("double precision");

                    b.Property<double>("AbstractProductId")
                        .HasColumnType("double precision");

                    b.Property<double>("EShopId")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbstractProductId");

                    b.HasIndex("EShopId");

                    b.ToTable("real_products", "comparison_engine");
                });

            modelBuilder.Entity("Domain.RealProduct", b =>
                {
                    b.HasOne("Domain.Product", "AbstractProduct")
                        .WithMany("RealProducts")
                        .HasForeignKey("AbstractProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EShop", "EShop")
                        .WithMany("RealProducts")
                        .HasForeignKey("EShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbstractProduct");

                    b.Navigation("EShop");
                });

            modelBuilder.Entity("Domain.EShop", b =>
                {
                    b.Navigation("RealProducts");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Navigation("RealProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
