name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild /home/runner/work/comparison_shopping_engine/comparison_shopping_engine/CheapShopWeb/CheapShopWeb.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
